// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU2eEGQQ7vV-mtZpn0j0TmIaRlAl1hkVw',
    appId: '1:916587102752:web:eb773f5e3c83b70db03245',
    messagingSenderId: '916587102752',
    projectId: 'harwarehuborg',
    authDomain: 'harwarehuborg.firebaseapp.com',
    storageBucket: 'harwarehuborg.appspot.com',
    measurementId: 'G-MME0FDN2WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKNA9nQacLORaOSmRT6v2iLOGTewlK80k',
    appId: '1:916587102752:android:b9e186296e234793b03245',
    messagingSenderId: '916587102752',
    projectId: 'harwarehuborg',
    storageBucket: 'harwarehuborg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV-16R6auCOlVyOkW-3svEI5SXCJWrD0U',
    appId: '1:916587102752:ios:a94afdbea801bbe0b03245',
    messagingSenderId: '916587102752',
    projectId: 'harwarehuborg',
    storageBucket: 'harwarehuborg.appspot.com',
    iosClientId: '916587102752-nsb4pptc9gd03o36pegjdh2bvohfv5em.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardwarehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV-16R6auCOlVyOkW-3svEI5SXCJWrD0U',
    appId: '1:916587102752:ios:a94afdbea801bbe0b03245',
    messagingSenderId: '916587102752',
    projectId: 'harwarehuborg',
    storageBucket: 'harwarehuborg.appspot.com',
    iosClientId: '916587102752-nsb4pptc9gd03o36pegjdh2bvohfv5em.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardwarehub',
  );
}
