// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLu7eOVfJxuahTPLmRsaQRNTUYYNV9ncM',
    appId: '1:57209626791:web:03124d0b7581cde2dc3b82',
    messagingSenderId: '57209626791',
    projectId: 'hardwarehub-2a75d',
    authDomain: 'hardwarehub-2a75d.firebaseapp.com',
    storageBucket: 'hardwarehub-2a75d.appspot.com',
    measurementId: 'G-SBRSPRKXKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5BE-ZHTYu38RU5_5jWs_rCCkygWg8AU',
    appId: '1:57209626791:android:ff4f90f090008f3cdc3b82',
    messagingSenderId: '57209626791',
    projectId: 'hardwarehub-2a75d',
    storageBucket: 'hardwarehub-2a75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanCdYe61Pja8KCX0-hYzpfiAEuDNiECU',
    appId: '1:57209626791:ios:72e48810dd35fb48dc3b82',
    messagingSenderId: '57209626791',
    projectId: 'hardwarehub-2a75d',
    storageBucket: 'hardwarehub-2a75d.appspot.com',
    iosClientId: '57209626791-srur0ce06bu17r59fjrrnal2f1fsued1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardwarehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanCdYe61Pja8KCX0-hYzpfiAEuDNiECU',
    appId: '1:57209626791:ios:72e48810dd35fb48dc3b82',
    messagingSenderId: '57209626791',
    projectId: 'hardwarehub-2a75d',
    storageBucket: 'hardwarehub-2a75d.appspot.com',
    iosClientId: '57209626791-srur0ce06bu17r59fjrrnal2f1fsued1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardwarehub',
  );
}
